{
  "accountId" : 25556,
  "userStatusID" : 1,
  "loginName" : "mikehimel",
  "firstName" : "Mike",
  "lastName" : "Himelstein",
  "email" : "qa-us@vocalocity.com",
  "phoneNumber" : "123456789",
  "role" : 0,
  "roleId" : [ 3 ],
  "secretQuestionId" : 4,
  "secretAnswer" : "QA",
  "dateLastUpdated" : "2011-02-18T18:37:33.788Z",
  "lastUpdatedByUserId" : 2884,
  "existingsuperuser" : 0,
  "contactnumbers" : [ {
    "userId" : 68005
  } ],
  "updateMeWithAnnouncements" : 0,
  "blockAccess" : 0,
  "userId" : 68005
}


